<a href="https://colab.research.google.com/github/Dylan-Brogdon/Statistics-Labs-2022/blob/main/Brogdon_Lab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Lab #3 Notebook

#Loops

In [ ]:
for i in range(10):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [1]:
#This counts 10 numbers starting from 0

In [ ]:
for i in range(5,8):
  print(i)

5
6
7


In [ ]:
for i in range(3):
  print( "Test Number: " , i )

Test Number:  0
Test Number:  1
Test Number:  2


In [ ]:
def square(x):
  return x**2

In [2]:
#We made a function that squares the variable x when we type out square(x)

In [ ]:
square(5)

25

In [ ]:
square(33)

1089

In [ ]:
square(square(5))

625

In [ ]:
square(square(square(square(square(square(square(square(5))))))))

86361685550944446253863518628003995711160003644362813850237034701685918031624270579715075034722882265605472939461496635969950989468319466936530037770580747746862471103668212890625

In [ ]:
def add_two(x):
  return x+2

In [3]:
#We made a function that adds two to whatever variable x is through add_two(x)

In [ ]:
add_two(5)

7

In [ ]:
square(add_two(5))

49

In [ ]:
choice = "orange"

In [ ]:
if choice == "apple":

  print("You choose apples.")

else:

  print("You did not choose apples.")

You did not choose apples.


In [4]:
#This is an if/else function where if we choose the word 'apple' it will tell us we did, but if we put anything else through the 'else' function it will say we did not choose apples.

In [ ]:
if choice == "apple":

  print("You choose apples.")
  print("Thank you, shop again!")

elif choice == "orange":

  print("You choose oranges.")
  print("Thank you, shop again!")

else:

  print("You did not choose apples or oranges.")

You choose oranges.
Thank you, shop again!


In [5]:
#This is the if/else function but with two 'if' functions. After the first if, it is then called elif

#User Input

In [ ]:
choice = input("Please enter your choice (i.e. apple): ")

Please enter your choice (i.e. apple): papaya


In [ ]:
choice

'papaya'

In [6]:
#We make a basic input command and ask for an input of produce

In [ ]:
if choice == "apple":

  print("You choose apples")

elif choice == "orange":

  print("You choose oranges")

elif choice == "papaya":

  print("You choose papayas")

else:

  print("You did not choose apples, oranges, or papayas")

You choose papayas


In [7]:
#We made an if/else function for the input function above

In [ ]:
import numpy as np

In [ ]:
np.random.permutation(52)

array([ 2, 11, 12, 49, 37, 21,  6, 14, 39, 41, 48, 18, 16,  3, 31, 27, 29,
       38, 26, 17, 33, 25,  7, 36, 46, 24, 43,  5, 13,  0,  9, 34, 47,  4,
       15, 20,  8, 10, 32, 42, 19, 50, 51, 45, 23, 44, 28, 30, 40,  1, 22,
       35])

In [ ]:
#This randomly orders the number of 0-51

In [ ]:
cards = np.random.permutation(52)

In [ ]:
cards

array([ 7, 36, 28, 48, 21, 30, 50,  8,  9, 22, 41, 19, 47, 18, 25, 29, 46,
       26, 39, 17, 13,  0, 20, 23, 45, 49,  1, 37, 16, 12,  2, 44,  3, 24,
       15, 35,  5,  6, 38, 32, 33, 34, 10, 42, 40, 14, 51, 43, 31, 27, 11,
        4])

In [ ]:
cards[0]

7

In [ ]:
cards[2]

28

In [8]:
#This just chooses what number was in the third slot

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

In [ ]:
np.arange(52).reshape(4,13)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [9]:
#We arrange this 52 cards to be in order

In [ ]:
np.arange(52).reshape(4,13)%13

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [11]:
#We then make it so it is 12 cards four times, to represent the numbers per suit

In [ ]:
np.arange(52).reshape(4,13)//13

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [13]:
#We then make it so each row has a number to match the suits, 0 = clubs and so on

In [ ]:
suits = ['Clubs','Spades','Hearts','Diamonds']
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King']

In [ ]:
suits

['Clubs', 'Spades', 'Hearts', 'Diamonds']

In [ ]:
suits[0]

'Clubs'

In [ ]:
names[1]

'Two'

In [ ]:
def card_name(card_number):

  suit = card_number//13
  name = card_number%13

  return names[name] + " of " + suits[suit]

In [14]:
#We made a command that gives us the number ranging from Ace to King and the suit put together

In [ ]:
card_name(0)

'Ace of Clubs'

In [ ]:
card_name(1)

'Two of Clubs'

In [ ]:
card_name(51)

'King of Diamonds'

In [ ]:
card_name(24)

'Queen of Spades'

In [ ]:
cards = np.random.permutation(52)

In [ ]:
top_of_deck            = card_name(cards[0])
second_card_in_deck    = card_name(cards[1])
last_card_in_deck      = card_name(cards[-1])

In [ ]:
top_of_deck,second_card_in_deck,last_card_in_deck

('Ten of Hearts', 'King of Diamonds', 'Three of Diamonds')

In [ ]:
for i in range(5):
  print(card_name(cards[i]))

Ten of Hearts
King of Diamonds
Eight of Clubs
Four of Hearts
Five of Clubs


In [ ]:
for i in range(15):
  print(card_name(cards[i]))

Ten of Hearts
King of Diamonds
Eight of Clubs
Four of Hearts
Five of Clubs
Ten of Clubs
King of Hearts
Queen of Diamonds
Jack of Spades
Ten of Spades
Six of Clubs
Ace of Clubs
Queen of Hearts
Three of Spades
Queen of Spades


In [15]:
#We randomize and ask to list out the first 15 cards and display them with the number and suit

In [ ]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/"
card_url_tail = ".png"

In [16]:
#This is where we get the images for the cards

In [ ]:
suit = ['k','p','s','l']
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k']

In [ ]:
i = np.random.randint(4)
j = np.random.randint(13)

In [ ]:
i,j

(3, 11)

In [ ]:
suit[i]

'l'

In [ ]:
card[i]

'4'

In [ ]:
from IPython.core.display import display, HTML

In [ ]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

In [ ]:
img = card_url_head + suit[i] + card[j] + card_url_tail

In [17]:
#Through this code we get the front and the back of the card to be able to be displayed

In [ ]:
show_img(img)